name: Bump Homebrew Cask on Release

on:
  workflow_dispatch:
  release:
    types:
      - published
      - edited

jobs:
  update-cask:
    runs-on: macos-latest

    steps:
      - name: Checkout Homebrew Tap
        uses: actions/checkout@v3
        with:
          repository: thusvill/homebrew-livewallpaper
          token: ${{ secrets.GH_PAT }}
          path: tap

      - name: Extract Version
        id: extract
        run: |
          VERSION="${GITHUB_REF#refs/tags/V}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Download Latest DMG/ZIP Asset
        run: |
           asset_url=$(gh release view --repo thusvill/LiveWallpaperMacOS --json assets -q '.assets[] | select(.name | test("\\.dmg$|\\.zip$")) | .url')
            curl -L "$asset_url" -o app_release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}


      - name: Compute SHA256 Checksum
        id: checksum
        run: |
          SHA256=$(shasum -a 256 app_release | awk '{print $1}')
          echo "sha256=$SHA256" >> "$GITHUB_OUTPUT"

      - name: Update Cask File
        run: |
          cd tap/Casks/l
          sed -i '' "s/^  version \".*\"/  version \"${{ steps.extract.outputs.version }}\"/" livewallpaper.rb
          sed -i '' "s/^  sha256 \".*\"/  sha256 \"${{ steps.checksum.outputs.sha256 }}\"/" livewallpaper.rb

      - name: Run brew style --fix
        run: |
          brew tap thusvill/livewallpaper ./tap
          brew style --fix tap/Casks/l/livewallpaper.rb

      - name: Commit and Push Changes
        run: |
          cd tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Casks/l/livewallpaper.rb
          git commit -m "Bump version to ${{ steps.extract.outputs.version }}"
          git push
