name: Bump Homebrew Cask on Release or Edit

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: macos-latest

    steps:
      - name: Checkout Homebrew Tap
        uses: actions/checkout@v3
        with:
          repository: thusvill/homebrew-livewallpaper
          token: ${{ secrets.GH_PAT }}
          path: tap

      - name: Extract Version and Asset URL
        id: extract
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/V}"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

          ASSET_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/V$VERSION \
            | jq -r '.assets[0].browser_download_url')

          if [[ "$ASSET_URL" == "null" ]]; then
            echo "Error: Could not find asset for version V$VERSION"
            exit 1
          fi

          echo "asset_url=$ASSET_URL" >> "$GITHUB_OUTPUT"

      - name: Download Release File
        run: |
          curl -L "${{ steps.extract.outputs.asset_url }}" -o asset.tar

      - name: Compute SHA256
        id: sha
        run: |
          SHA=$(shasum -a 256 asset.tar | awk '{ print $1 }')
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: Update Cask File
        run: |
          cd tap/Casks/l
          sed -i '' "s/^  version \".*\"/  version \"${{ steps.extract.outputs.version }}\"/" livewallpaper.rb
          sed -i '' "s/^  sha256 \".*\"/  sha256 \"${{ steps.sha.outputs.sha }}\"/" livewallpaper.rb

      - name: Run brew style --fix
        run: |
          brew tap thusvill/livewallpaper ./tap
          brew style --fix tap/Casks/l/livewallpaper.rb

      - name: Commit and Push Changes
        run: |
          cd tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Casks/l/livewallpaper.rb
          git commit -m "Bump version to ${{ steps.extract.outputs.version }}"
          git push
