name: Bump Homebrew Cask on Release

on:
  workflow_dispatch:
  release:
    types:
      - published
      - edited
jobs:
  update-cask:
    runs-on: macos-latest

    steps:
      - name: Checkout Homebrew Tap
        uses: actions/checkout@v3
        with:
          repository: thusvill/homebrew-livewallpaper
          token: ${{ secrets.GH_PAT }}
          path: tap

      - name: Extract Version
        id: extract
        run: |
          # Extract version number from tag (strip leading 'V' if exists)
          VERSION="${GITHUB_REF#refs/tags/V}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Download latest release asset
        id: download_asset
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Get URL of latest dmg or zip release asset
          asset_url=$(gh release view --repo thusvill/LiveWallpaperMacOS --json assets -q '.assets[] | select(.name | test("\\.dmg$|\\.zip$")) | .url')
          echo "Asset URL: $asset_url"
          curl -L "$asset_url" -o latest_asset

      - name: Calculate SHA256 checksum
        id: sha256
        run: |
          sha256sum=$(shasum -a 256 latest_asset | awk '{print $1}')
          echo "sha256=$sha256sum" >> "$GITHUB_OUTPUT"

      - name: Update Cask File with Version and SHA256
        run: |
          cd tap/Casks/l
          sed -i '' "s#^  version \".*\"#  version \"${{ steps.extract.outputs.version }}\"#" livewallpaper.rb
          sed -i '' "s#^  sha256 \".*\"#  sha256 \"${{ steps.sha256.outputs.sha256 }}\"#" livewallpaper.rb

      - name: Run brew style --fix
        run: |
          brew tap thusvill/livewallpaper ./tap
          brew style --fix tap/Casks/l/livewallpaper.rb

      - name: Commit and Push Changes
        run: |
          cd tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Casks/l/livewallpaper.rb
          git commit -m "Bump version to ${{ steps.extract.outputs.version }} with new sha256"
          git push
